### PR TITLE
python3 compatibility for bsg_round_robin_arb

### PR DESCRIPTION
**Pull request by adithyasunil26**
Modified the `print` statements to be compatible with python 3. `from __future__ import print_function` will ensure the script continues to be compatible with python 2.

### CODE REVIEW

**Comment by dpetrisko** [comment]
Thanks! Can you rebase for resolve the conflict? Have you verified that this produces the same round robin output as currently in the repo (no git diff)?

**Comment by adithyasunil26** [comment]
> Thanks! Can you rebase for resolve the conflict? 

I have fixed the conflict.

> Have you verified that this produces the same round robin output as currently in the repo (no git diff)?

Yes I have verified that there are no differences between the output and the current `bsg_round_robin_arb.v`

**Review by dpetrisko — APPROVED** [review]

**Comment by dpetrisko** [comment]
@taylor-bsg look good to you?

**Review by taylor-bsg — APPROVED** [review]
LGTM; I know nothing about Python =)

**Comment by taylor-bsg** [comment]
Needs to be rebased? @dpetrisko

**Comment by dpetrisko** [comment]
Thanks @adithyasunil26 ! we merged with #541 to get rid of some weird git merging

**Pull request closed without merging**
