### PR TITLE
[bsg_cache] ready_o -> yumi_o

### PR DESCRIPTION
**Pull request by tommydcjung**
Fixing the input handshaking interface.

### CODE REVIEW

**Comment by farzamgl** [comment]
Is there a reason behind switching from ready to yumi?

**Comment by tommydcjung** [comment]
It's more suitable to call it yumi_o, because it depends on the input packet and v_i.
https://github.com/bespoke-silicon-group/basejump_stl/blob/4958d731df66cd2654738c68192dd642acedec81/bsg_cache/bsg_cache.v#L991

**Comment by dpetrisko** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/issues/605

See here (and linked issue) for further discussion

**Comment by farzamgl** [comment]
Makes sense. The changes look good.

**Review by farzamgl — APPROVED** [review]

**Comment by taylor-bsg** [comment]
Looping in @BrendenPage to sign off on it =)

**Comment by BrendenPage** [comment]
Looks good to me!

**Comment by taylor-bsg** [comment]
@BrendenPage do you have to pull these changes into BaseJump STL 2.0?

**Comment by BrendenPage** [comment]
> @BrendenPage do you have to pull these changes into BaseJump STL 2.0?

I was considering merging the master branch into Basejump 2.0 along with these changes but I can specifically pull this branch in instead if that's better @taylor-bsg.

**Pull request merged**
