### PR TITLE
Update to bsg_dlatch

### PR DESCRIPTION
**Pull request by stdavids**
Addressing issues #38 and #21.

Adding the i_know_this_is_a_bad_idea_p parameter and warning. Changed en_i port to clk_i. Refactored to use always_latch rather than always_ff.

### CODE REVIEW

**Comment by stdavids** [comment]
Not sure I follow, there is just a single initial statement for the warning...

**Comment by taylor-bsg** [comment]
Ah got it .. it was how the app was showing it. Probably better to use
assert instead of if statement?

**Comment by stdavids** [comment]
Done, moved to using assert. I also surrounded it in translate_off / translate_on pragmas because with asserts there are no parameterizations that would remove the warning of initial statements during synthesis analysis.

**Comment by taylor-bsg** [comment]
Sorry I did not understand this last part?

**Comment by dpetrisko** [comment]
Oh interesting. Are you saying you can't conditionally generate asserts?

**Comment by stdavids** [comment]
Initial statements and assert statements throw warnings in DC. Before, I used a generate if statement surrounding an initial statement so if that if statement resolves to false the initial statement will not be instantiated and DC is happy thus I didn't use translate pragmas because if you are not consenting that this is a bad idea, DC will throw a warning which is nice.

Moving to assert, if the statement resolves to true or false, DC still throws a warning. There is no parameterization that stops DC throwing a warning therefore I surrounded it with translate pragmas.

**Comment by dpetrisko** [comment]
Came across this about "elaboration system tasks": 

image

https://www.veripool.org/issues/1429-Verilator-Feature-request-elaboration-tasks#change-4871

**Comment by stdavids** [comment]
Hey Dan, I'm assuming that your suggestion is to move error to fatal? I like that idea, that will kill vcs if you do not acknowledge that the latch is a bad idea.

However this will have no effect on DC's elaboration and has no affect the aforementioned translate off pragmas, you'll simply get a VER-281 saying that the initial block is ignored.

**Comment by dpetrisko** [comment]
Admittedly I haven’t tested it out, but according to this it sounds like if you put the code in the generate if _instead_ of an initial block, it flags it at elaboration instead of simulation. So DC might do the right thing / not complain since there’s no initial block

**Comment by stdavids** [comment]
Ah I see, very interesting. I just tested in DC and VCS and this works well however we cannot use the %m in the message, presumably because it doesn't know the full hierarchical path yet. With that said, VCS does actually print the hier path just below the error and you can figure out the path via the DC log albeit not as clear as VCS. I'm in favor of this over the previous two implementations!

**Comment by stdavids** [comment]
Oh, I should also note that to get this to work in VCS you need to add the `-assert svaext` flag. If you don't have that flag, it errors as a syntax error regardless of parameterization.

**Comment by dpetrisko** [comment]
Nice! I just checked and Verilator seems fine with the syntax with no additional flags

**Comment by taylor-bsg** [comment]
Going to merge...

**Pull request merged**
