### PR TITLE
Adding debug_p parameter to control how verbose the display messages are.

### PR DESCRIPTION
**Pull request by stdavids**
Continued from PR #263 

Moved changes to bsg_test/bsg_trace_replay.v. Addressed the feedback by having multiple debug levels with comments about what level does what. More explicit begin-end to remove scope ambiguity.

### CODE REVIEW

**Comment by dpetrisko** [comment]
Changes look good to me. Possibly out of scope: we could add BSG_LEVEL_NONE BSG_LEVEL_ERROR, BSG_LEVEL_INFO, BSG_LEVEL_VERBOSE to bsg_defines as standard debug levels

**Comment by taylor-bsg** [comment]
Maybe add as an issue: standard debug levels?  One idea to throw in there
is that we could have a bit vector with common cases (which we would have
to identify.)

**Comment by Xusine1131** [comment]
Maybe we can refer to UVM_INFO and build a similar function printing message with a given debug level?

**Comment by tommydcjung** [comment]
Can the case statement with default case (line 210), be merged with the case statement above it? so that the code is left cleaner than it was found.

**Comment by taylor-bsg** [comment]
Good pointer Shanqing!

**Pull request merged**
