### PR TITLE
 bsg_fsb_node_trace_replay.v print wall time

### PR DESCRIPTION
**Pull request by tommydcjung**
bsg_fsb_node_trace_replay.v used in bsg_tag_trace_replay

### CODE REVIEW

**Comment by drichmond** [comment]
@taylor-bsg I would be interested in seeing your version. I was considering making a general comment earlier:

This is becoming a common pattern in BSG. Perhaps we should have a module that prints current timestamps based on an event. However, one issue is that output file could be stomped on by different modules -- particularly in multi-threaded environments.

I suspect your version fixes my second thought

**Comment by mrutt92** [comment]
I wrote pretty much an exact copy of this code in hb_bigblade. Echoing @drichmond point, we might want to have a function or macro to do this?

**Comment by tommydcjung** [comment]
I think we might as well make a dpi version that is easy to include, so that it doesn't write to some file and parse it back.

**Comment by taylor-bsg** [comment]
Hi, as mentioned I have solution for this that avoids the file stuff and DPI, we just read directly /proc/uptime. I can commit it later tonight.

**Comment by taylor-bsg** [comment]
I committed the code

**Comment by taylor-bsg** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/commit/57553c53cda0d825ee3f576cc879e84e26726330

**Comment by taylor-bsg** [comment]
Already merged.

**Pull request closed without merging**
