### PR TITLE
DRAMSim3 moves macros from source to header

### LINKED ISSUE #368: macro defines in package
https://github.com/bespoke-silicon-group/basejump_stl/blob/d4cd62042e6f83b953a6bad75c2257f10ce0c853/bsg_test/bsg_dramsim3_pkg.v#L86

This means that the correct operation of this module will depend on its include order on the VCS command line. We should factor out into a .vh file and include appropriately.

### PR DESCRIPTION
**Pull request by mrutt92**
Fixes #368

### CODE REVIEW

**Comment by taylor-bsg** [comment]
@mrutt92 will this break anything when I merge it?

**Comment by mrutt92** [comment]
Nope.

**Review by dpetrisko — APPROVED** [review]

**Comment by dpetrisko** [comment]
I think it requires minor changes in BlackParrot. Everywhere bsg_dramsim3_pkg is currently used needs an `include bsg_dramsim3.vh now. Not an objection to the merge, I wrote a note to remind myself when we bump basejump.  (I think bsg_manycore uses global includes, so as long as this is added to the makefile flist, should be fine)

**Comment by mrutt92** [comment]
What's the status on this?

**Review by farzamgl — APPROVED** [review]
Everything should work with minimal change on BlackParrot, so there's no problem in my view.

**Comment by mrutt92** [comment]
@taylor-bsg I don't have permissions to merge this but it has been approved by the BP folks.

**Pull request merged**
