### PR TITLE
efficient implementation of lru_encode

### PR DESCRIPTION
**Pull request by tommydcjung**
Good evening,

Here is the basic idea. the efficient implementation only needs 4 of 2-to-1 muxes at most.
the current implementation causes huge critical path in the cache design. 

lru_encode

### CODE REVIEW

**Comment by tommydcjung** [comment]
@farzamgl can you review this?

**Comment by dpetrisko** [comment]
I'll take a closer look tomorrow, but is the LRU algorithm the same after this change or no? Has the state coverage changed?

**Comment by tommydcjung** [comment]
the algorithm is the same. the hardware is actually pretty simple if you look at it.

**Comment by dpetrisko** [comment]
LGTM; maybe put a link to/embed to the LRU table in the header comment

**Pull request merged**
