### PR TITLE
Fix in bsg_mem_1rw_sync_mask_write_bit_synth for Verilator

### PR DESCRIPTION
**Pull request by dpetrisko**

### CODE REVIEW

**Comment by dpetrisko** [comment]
High priority PR to fix BlackParrot build

**Comment by black-parrot** [comment]
Hi, I feel like this is cart driving horse. We can not commit this unless the PPA impact is evaluated. There are many rams that are synthesized in our designs, and this could seriously hurt our PPA across all of our designs.

I suggest either we put some ifdef VERILATOR_POS in there, or create a verilator_pos hard target, or .. just fix Verilator.

**Comment by dpetrisko** [comment]
True. There’s an ifdef for verilator, so that’s no problem. Will update tonight

**Comment by black-parrot** [comment]
Great, Dan! Having a regression that evaluates PPA is on our todo list.

**Comment by dpetrisko** [comment]
Fixed for now, with a Verilator ifdef

**Comment by black-parrot** [comment]
Maybe say what Verilator version this fix is for.

**Pull request merged**
