### PR TITLE
Yet again, trying to fix the FPU warnings in FPGA compilation

### PR DESCRIPTION
**Pull request by drichmond**
The FPGA warnings came back in the FPU unit. So... I took a hammer and fixed them again.

### CODE REVIEW

**Comment by taylor-bsg** [comment]
What changed?

**Comment by drichmond** [comment]
Vivado 2019.1

But I suspect nothing changed. I had to switch syntaxes to a newer, supported one.

**Comment by drichmond** [comment]
This fixed the issue in Vivado. Good to go?

**Comment by dpetrisko** [comment]
Verilator seems fine with it

**Pull request merged**
