### PR TITLE
[bsg_cache_non_blocking] bug fix for clearing dirty bits

### PR DESCRIPTION
**Pull request by tommydcjung**
Bug: dirty bits is not cleared when miss handling without any store miss completes.
Fix: added e_stat_set_lru_and_clear_dirty option to stat_mem, and fixed the logic in MHU FSM.

### CODE REVIEW

**Comment by tommydcjung** [comment]
That's right. the coverage report will have some false negatives, and the person who checks needs to manually go through each coverage hole and decide whether it can be waived or not. This saves the repeats.

**Comment by drichmond** [comment]
Is there a python test that can expose this?

**Comment by tommydcjung** [comment]
This is not a correctness bug, but a performance bug. There is no direct way to check that, unless running some experiments.

**Comment by drichmond** [comment]
Ah, got it.

**Comment by drichmond** [comment]
Looks good to me then

**Pull request merged**
