### PR TITLE
set max input to 32

### PR DESCRIPTION
**Pull request by tommydcjung**
It might not be a good setting for synthesis, but still can be needed for testbench/simulation.

### CODE REVIEW

**Comment by tommydcjung** [comment]
I guess it affects reading the file and elaborating, but generate if-else shouldn't be much of problem?

**Comment by drichmond** [comment]
I honestly don't know. Do you want me to test compile times in VCS and Verilator?

**Comment by dpetrisko** [comment]
I think it depends if Verilator uses #ifdef or if else for generate statements. Interesting question

**Comment by taylor-bsg** [comment]
I think Dan was saying that compile times for case statements can be out of
control for Verilator.

Presumably Tommy can do a quick test.

M

**Comment by dpetrisko** [comment]
Yeah that's #209.  The problem there is each line of the case statement is actually used, so it ends up being a super large C function.  Presumably, parameters are optimized better, because unused parameter paths are "dead code" in the model.  But a quick experiment could verify

**Comment by tommydcjung** [comment]
As far as I know, this has no impact on DC.

**Pull request closed without merging**
