### PR TITLE
Switch to BSG External version of DRAMSim3

### PR DESCRIPTION
**Pull request by drichmond**
Contains our changes

### CODE REVIEW

**Comment by drichmond** [comment]
This passes the dramsim3_bandwidth and dramsim3_bandwidth2 tests in testing, passes regression in replicant in Verilator and VCS with timing_v0_8_4.

**Comment by tommydcjung** [comment]
Shouldn't you be creating a separate branch in this fork , instead of updating the master?

**Comment by drichmond** [comment]
Is that what you want me to do? Happy to do it

**Comment by tommydcjung** [comment]
It will be better if there are any new changes coming from the original.

**Comment by drichmond** [comment]
Good point. When you say original, you mean the UMD repository, right?

**Comment by drichmond** [comment]
Done! And I reverted master to its original state

**Comment by tommydcjung** [comment]
I don't think the new branch should contain this commit, which basically resets all files.
https://github.com/bsg-external/DRAMsim3/commit/4d755992be83bd8e6f67d0b7ca8db92a3aae761c

**Comment by drichmond** [comment]
How on earth...

**Comment by drichmond** [comment]
I'm not seeing that. How are you seeing that?

**Pull request merged**
