### PR TITLE
Add DRAMSIM3 makefile

### PR DESCRIPTION
**Pull request by dpetrisko**
So users don't have to figure it out for themselves

### CODE REVIEW

**Review by mrutt92 — APPROVED** [review]
I prefer to torture our users... but if you insist.

**Comment by drichmond** [comment]
For maximum effectiveness you should obfuscate the makefile

**Comment by dpetrisko** [comment]
good to go?

**Comment by dpetrisko** [comment]
The only other place I could see is toplevel,  but I think it makes more sense in bsg_test

**Comment by mrutt92** [comment]
you could name it libdramsim3.mk and folks can use the `-f` flag.

**Comment by dpetrisko** [comment]
>you could name it libdramsim3.mk and folks can use the -f flag

Done

**Review by taylor-bsg — APPROVED** [review]

**Pull request merged**
