### PR TITLE
nonsynth mem using associative array

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by taylor-bsg** [comment]
Looks great, put a comment in the header that this is for simulating
arbitrarily large memories.

**Comment by dpetrisko** [comment]
Can we put an ifndef VERILATOR elaboration assertion that errors if you try to instantiate? (Similar to bsg_dlatch). Verilator doesn’t support associative arrays

**Comment by tommydcjung** [comment]
it will fail to compile regardless, so I think it's fine without it?

**Comment by dpetrisko** [comment]
Yeah, but it’s a more informative error. Makes it clear to the user that we know it’s unsupported

**Comment by dpetrisko** [comment]
Not a showstopper though, just a thought

**Pull request merged**
