### PR TITLE
Allowing readmemh or readmemb in test rom

### PR DESCRIPTION
**Pull request by dpetrisko**
title

### CODE REVIEW

**Comment by drichmond** [comment]
Rad. 

Have you tested that this works? I can run it in Verilator in a bit

**Comment by dpetrisko** [comment]
Testing it now. It compiles though, which is half the battle :P

**Comment by drichmond** [comment]
More than half, IMO

**Comment by dpetrisko** [comment]
Works in both VCS and Verilator

**Comment by dpetrisko** [comment]
good to go?

**Pull request merged**
