### PR TITLE
Switch bsg_nonsynth_reset_gen input/output to bit instead of (implicit) logic to spurious pos/neg edges at T=0

### PR DESCRIPTION
**Pull request by drichmond**
Switched input and output of nonsynth_reset_gen to bit (instead of logic)

In newer versions of VCS, casting between logic and bit types triggers new positive/negative edges at T=0 when 'x' -> '1/0'. 

To solve this (and be backward compatible) this PR changes the type of `clk_i` and `async_reset_o` to bit so that users can use bits in the instantiating module and avoid negative/positive edges, or use logic and maintain the old behavior.

Replaces #376

### CODE REVIEW

**Review by dpetrisko — APPROVED** [review]

**Comment by taylor-bsg** [comment]
Add a comment explaining why input bit is used.

// This module relies on the input clock wires starting at 0 at time 0
// and not transitioning from X to 0 at time 0, causing a spurious negedge
// to accomplish this in > VCS 2020, we have to be sure that the input is declare as bit.
// Moreover, the expectation is that this module's input comes from a clock generation
// module that uses bit, such as bsg_nonsynth_clk_gen

**Comment by drichmond** [comment]
OK! That comment?

**Comment by taylor-bsg** [comment]
yes

**Comment by drichmond** [comment]
Done (with small modifications)

**Review by taylor-bsg — APPROVED** [review]

**Pull request merged**
