### PR TITLE
Adding axi mem for testing

### PR DESCRIPTION
**Pull request by dpetrisko**
Pulled from https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/testbenches/common/v/bsg_nonsynth_manycore_axi_mem.v

### CODE REVIEW

**Review by taylor-bsg — COMMENTED** [review]
@drichmond @tommydcjung do we use this currently in manycore? Is there a corresponding pull request to switch over to this version?

**Comment by dpetrisko** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/pull/478

**Comment by tommydcjung** [comment]
ci_bigblade does not have axi mem, so I think it's fine

**Comment by drichmond** [comment]
Pretty sure it's dead in replicant too. It was removed in this commit: https://github.com/bespoke-silicon-group/bsg_replicant/commit/7c02428a0063b0232591613792991d5d3fb3e66a

**Review by drichmond — APPROVED** [review]
This looks fine to me. We don't use it in manycore, or in replicant at this point. 

Was it in pre-bigblade testbenches for a particular memory configuration

**Comment by dpetrisko** [comment]
if (mem_cfg_lp[e_vcache_blocking_axi4_nonsynth_mem]
     | mem_cfg_lp[e_vcache_non_blocking_axi4_nonsynth_mem]) begin: lv3_axi_mem
     
     These two

**Pull request merged**
