### PR TITLE
Stat to tag_mem crit path

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
```
dc_shell> report_timing -from [get_pin cache/stat_mem/clk_i] -to [get_pin -of_object [get_cells cache/tag_mem/macro_mem]]
 
****************************************
Report : timing
        -path full
        -delay max
        -max_paths 1
Design : bsg_manycore_vcache_blocking
Version: O-2018.06-SP4
Date   : Wed Jun  3 15:20:01 2020
****************************************

Operating Conditions: asd   Library: asd
Wire Load Model Mode: top
No paths.

```

**Comment by taylor-bsg** [comment]
So in the end, what was the resolution? Were you able to break the path
without increasing cache miss latency?

**Comment by tommydcjung** [comment]
The resolution is to delay the tag update until the fill data has been all received/moving to RECOVER.

**Comment by taylor-bsg** [comment]
Ah! Got it.

**Pull request merged**
