### PR TITLE
Redirecting to public version of dramsim3

### PR DESCRIPTION
**Pull request by dpetrisko**
Minor thing: The remote repo is called "DRAMsim3" not "DRAMSim3".  We should probably update paths to avoid any weird issues in the future.

### CODE REVIEW

**Comment by mrutt92** [comment]
We made some edits - we might want to make a public fork of UMDs version and checkin our changes.

**Comment by dpetrisko** [comment]
That works as well.  Or make a PR back ;)

**Comment by dpetrisko** [comment]
@mrutt92 , I added a public fork to bsg-external, if you want to put your changes up there and bump the submodule

**Comment by drichmond** [comment]
Fixed in #304 ?

**Comment by dpetrisko** [comment]
I mean yeah, seeing as it's the same change :)

**Comment by drichmond** [comment]
Same, but with some of the changes we made added on

**Pull request closed without merging**
