### PR TITLE
bsg_fifo_1r1w_small bsg_two_fifo for unhardened

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
bsg_two_fifo is slightly better in terms of area.

**Comment by dpetrisko** [comment]
Maybe also sub bsg_one_fifo?

**Comment by taylor-bsg** [comment]
Nice Tommy! Thanks!

I vaguely remember optimizing critical paths in bsg_two_fifo as well.

**Comment by taylor-bsg** [comment]
I will approve and merge. Tommy, it would be nice if we can incorporate Dan's suggestion. I did confirm that bsg_fifo_1r1w_small does seem to work for the case of 1 element, so we might as well slide in the optimized code from bsg_one_fifo. This use of specialization is one of the core features in BaseJump STL.

**Pull request merged**
