### PR TITLE
Change bsg_wormhole_router to rv& via output_control

### PR DESCRIPTION
**Pull request by dpetrisko**
Needs testing

### CODE REVIEW

**Comment by dpetrisko** [comment]
Thanks Paul!

**Comment by hema0730** [comment]
This perfectly eliminated feedthrough paths in bp_tile_node.

**Comment by taylor-bsg** [comment]
Does this comment need to be updated? This should be a perfectly normal condition now?

https://github.com/bespoke-silicon-group/basejump_stl/blob/0e3313335586c399c839249364fc209a6b45cb74/bsg_noc/bsg_wormhole_router.v#L228

M

**Comment by dpetrisko** [comment]
>Does this comment need to be updated? This should be a perfectly normal condition now?

Maybe we should change the assertion into a display?

**Comment by gaozihou** [comment]
> > Does this comment need to be updated? This should be a perfectly normal condition now?
> 
> Maybe we should change the assertion into a display?

Assertion updated!

**Pull request merged**
